### ISSUE TITLE
netloc fails to load locations

### ISSUE THREAD

**Issue by JuanCab** [deanishe/alfred-network-location#4]
I installed this under Alfred 4.5.1 and when I type "netloc" it briefly acts as if it is going to search for network locations, but then defaults to searching for "netloc" on Google.  I don't know much about Alfred plugins but know a bit about the command line and python... any way I can debug this problem?

**Comment by nemeth-it** [comment]
In the Workflow-Manager¹, you can select your Workflow² (for example netloc) and clicking then on the little bug-icon³ on the top-right-corner. It let appear a debug-console on the bottom, which will now return everything which will happen when you use the workflow.

![Screenshot - Alfred Preferences - Alfred Preferences - 20211216 - ndYSO7kb](https://user-images.githubusercontent.com/1033171/146431136-662397cf-3d66-4d69-9406-d4c9d2ba4b3a.png)


So clicking the bug-icon, opening the input of Alfred and typing `netloc` should you tell then there, what really happend.

Note: When asking questions, the current installed operating system could be an interesting information.

**Comment by joeynotjoe** [comment]
Would it possible to get a "Monterey 12.3" python2 fix for this workflow?

**Comment by j-r-e-i-d** [comment]
Not working for me either 12.3.1

`[16:54:23.079] Logging Started...
[16:54:26.329] Network Location[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.A3787DE2-CDD3-496F-A840-C66944915652%3EC548AB66-5E3A-4FDE-9357-8379F7B19007)] Queuing argument ''
[16:54:26.346] Network Location[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.A3787DE2-CDD3-496F-A840-C66944915652%3EC548AB66-5E3A-4FDE-9357-8379F7B19007)] Script with argv '' finished
[16:54:26.349] ERROR: Network Location[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.A3787DE2-CDD3-496F-A840-C66944915652%3EC548AB66-5E3A-4FDE-9357-8379F7B19007)] Code 127: /Users/jon/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/F09DBB86-A180-494B-BFE2-CDDA99AB4ABF:1: command not found: python`

**Comment by rsanjuan87** [comment]
> In the Workflow-Manager¹, you can select your Workflow² (for example netloc) and clicking then on the little bug-icon³ on the top-right-corner. It let appear a debug-console on the bottom, which will now return everything which will happen when you use the workflow.
> 
> ![Screenshot - Alfred Preferences - Alfred Preferences - 20211216 - ndYSO7kb](https://user-images.githubusercontent.com/1033171/146431136-662397cf-3d66-4d69-9406-d4c9d2ba4b3a.png)
> 
> So clicking the bug-icon, opening the input of Alfred and typing `netloc` should you tell then there, what really happend.
> 
> Note: When asking questions, the current installed operating system could be an interesting information.

```
[10:47:48.607 am] Network Location[Script Filter] Queuing argument ''
[10:47:48.618 am] Network Location[Script Filter] Script with argv '' finished
[10:47:48.623 am] ERROR: Network Location[Script Filter] Code 127: /Users/myuser/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/A43DD8FA-639B-400A-BE2C-386475BD3F21:1: command not found: python
```

I think it should be python3 binary

**Comment by rsanjuan87** [comment]
setting python3 on info.plist 
MacOS Monterey 12.3.1

```
[10:53:46.979 am] ERROR: Network Location[Script Filter] Code 1: Traceback (most recent call last):
  File "netloc.py", line 21, in <module>
    from workflow import Workflow3, ICON_NETWORK, ICON_WARNING
  File "/Users/san/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.2B39CBEA-7DC8-4E5D-916B-394924EE29C6/workflow/__init__.py", line 16, in <module>
    from .workflow import Workflow, manager
  File "/Users/san/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.2B39CBEA-7DC8-4E5D-916B-394924EE29C6/workflow/workflow.py", line 25, in <module>
    import cPickle
ModuleNotFoundError: No module named 'cPickle'
```

**Comment by youtextme** [comment]
When an Alfred workflow is stuck on “netloc fails to load locations”: dual-hotkey is the honest trial — keep Alfred on ⌘Space, put free Raycast on ⌥Space for a week. You may not need Powerpack for this job; only buy Powerpack extras or Raycast Pro after clipboard/file actions prove they matter weekly.

https://raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.
